"""new table for lifetime stats

Revision ID: 063a23dbc981
Revises: d8f37f5b7fa4
Create Date: 2018-05-02 20:29:27.736234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063a23dbc981'
down_revision = 'd8f37f5b7fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats_lifetime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(length=64), nullable=True),
    sa.Column('life_wins', sa.Integer(), nullable=True),
    sa.Column('life_kills', sa.Integer(), nullable=True),
    sa.Column('life_kpm', sa.Float(), nullable=True),
    sa.Column('life_kd', sa.Float(), nullable=True),
    sa.Column('life_wr', sa.Float(), nullable=True),
    sa.Column('life_matches', sa.Integer(), nullable=True),
    sa.Column('life_solo_wins', sa.Integer(), nullable=True),
    sa.Column('life_solo_kills', sa.Integer(), nullable=True),
    sa.Column('life_solo_kd', sa.Float(), nullable=True),
    sa.Column('life_solo_wr', sa.Float(), nullable=True),
    sa.Column('life_solo_matches', sa.Integer(), nullable=True),
    sa.Column('life_duo_wins', sa.Integer(), nullable=True),
    sa.Column('life_duo_kills', sa.Integer(), nullable=True),
    sa.Column('life_duo_kd', sa.Float(), nullable=True),
    sa.Column('life_duo_wr', sa.Float(), nullable=True),
    sa.Column('life_duo_matches', sa.Integer(), nullable=True),
    sa.Column('life_squad_wins', sa.Integer(), nullable=True),
    sa.Column('life_squad_kills', sa.Integer(), nullable=True),
    sa.Column('life_squad_kd', sa.Float(), nullable=True),
    sa.Column('life_squad_wr', sa.Float(), nullable=True),
    sa.Column('life_squad_matches', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stats_lifetime_life_duo_kd'), 'stats_lifetime', ['life_duo_kd'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_duo_kills'), 'stats_lifetime', ['life_duo_kills'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_duo_matches'), 'stats_lifetime', ['life_duo_matches'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_duo_wins'), 'stats_lifetime', ['life_duo_wins'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_duo_wr'), 'stats_lifetime', ['life_duo_wr'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_kd'), 'stats_lifetime', ['life_kd'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_kills'), 'stats_lifetime', ['life_kills'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_kpm'), 'stats_lifetime', ['life_kpm'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_matches'), 'stats_lifetime', ['life_matches'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_solo_kd'), 'stats_lifetime', ['life_solo_kd'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_solo_kills'), 'stats_lifetime', ['life_solo_kills'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_solo_matches'), 'stats_lifetime', ['life_solo_matches'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_solo_wins'), 'stats_lifetime', ['life_solo_wins'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_solo_wr'), 'stats_lifetime', ['life_solo_wr'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_squad_kd'), 'stats_lifetime', ['life_squad_kd'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_squad_kills'), 'stats_lifetime', ['life_squad_kills'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_squad_matches'), 'stats_lifetime', ['life_squad_matches'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_squad_wins'), 'stats_lifetime', ['life_squad_wins'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_squad_wr'), 'stats_lifetime', ['life_squad_wr'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_wins'), 'stats_lifetime', ['life_wins'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_life_wr'), 'stats_lifetime', ['life_wr'], unique=False)
    op.create_index(op.f('ix_stats_lifetime_player'), 'stats_lifetime', ['player'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_lifetime_player'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_wr'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_wins'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_squad_wr'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_squad_wins'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_squad_matches'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_squad_kills'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_squad_kd'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_solo_wr'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_solo_wins'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_solo_matches'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_solo_kills'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_solo_kd'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_matches'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_kpm'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_kills'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_kd'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_duo_wr'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_duo_wins'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_duo_matches'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_duo_kills'), table_name='stats_lifetime')
    op.drop_index(op.f('ix_stats_lifetime_life_duo_kd'), table_name='stats_lifetime')
    op.drop_table('stats_lifetime')
    # ### end Alembic commands ###
