"""new table for season4

Revision ID: 096e9653b7a4
Revises: c590b7bd7585
Create Date: 2018-05-01 17:01:46.646518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096e9653b7a4'
down_revision = 'c590b7bd7585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats_four',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s4_solo_wins', sa.Integer(), nullable=True),
    sa.Column('s4_solo_kills', sa.Integer(), nullable=True),
    sa.Column('s4_solo_kd', sa.Float(), nullable=True),
    sa.Column('s4_solo_wr', sa.Float(), nullable=True),
    sa.Column('s4_solo_matches', sa.Integer(), nullable=True),
    sa.Column('s4_duo_wins', sa.Integer(), nullable=True),
    sa.Column('s4_duo_kills', sa.Integer(), nullable=True),
    sa.Column('s4_duo_kd', sa.Float(), nullable=True),
    sa.Column('s4_duo_wr', sa.Float(), nullable=True),
    sa.Column('s4_duo_matches', sa.Integer(), nullable=True),
    sa.Column('s4_squad_wins', sa.Integer(), nullable=True),
    sa.Column('s4_squad_kills', sa.Integer(), nullable=True),
    sa.Column('s4_squad_kpm', sa.Float(), nullable=True),
    sa.Column('s4_squad_kd', sa.Float(), nullable=True),
    sa.Column('s4_squad_wr', sa.Float(), nullable=True),
    sa.Column('s4_squad_matches', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stats_four_s4_duo_kd'), 'stats_four', ['s4_duo_kd'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_duo_kills'), 'stats_four', ['s4_duo_kills'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_duo_matches'), 'stats_four', ['s4_duo_matches'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_duo_wins'), 'stats_four', ['s4_duo_wins'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_duo_wr'), 'stats_four', ['s4_duo_wr'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_solo_kd'), 'stats_four', ['s4_solo_kd'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_solo_kills'), 'stats_four', ['s4_solo_kills'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_solo_matches'), 'stats_four', ['s4_solo_matches'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_solo_wins'), 'stats_four', ['s4_solo_wins'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_solo_wr'), 'stats_four', ['s4_solo_wr'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_squad_kd'), 'stats_four', ['s4_squad_kd'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_squad_kills'), 'stats_four', ['s4_squad_kills'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_squad_kpm'), 'stats_four', ['s4_squad_kpm'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_squad_matches'), 'stats_four', ['s4_squad_matches'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_squad_wins'), 'stats_four', ['s4_squad_wins'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_squad_wr'), 'stats_four', ['s4_squad_wr'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_four_s4_squad_wr'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_squad_wins'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_squad_matches'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_squad_kpm'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_squad_kills'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_squad_kd'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_solo_wr'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_solo_wins'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_solo_matches'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_solo_kills'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_solo_kd'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_duo_wr'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_duo_wins'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_duo_matches'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_duo_kills'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_duo_kd'), table_name='stats_four')
    op.drop_table('stats_four')
    # ### end Alembic commands ###
