"""adding s4 total stats

Revision ID: 1508333f895d
Revises: 063a23dbc981
Create Date: 2018-05-03 01:22:29.075265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1508333f895d'
down_revision = '063a23dbc981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats_four', sa.Column('s4_total_kills', sa.Integer(), nullable=True))
    op.add_column('stats_four', sa.Column('s4_total_matches', sa.Integer(), nullable=True))
    op.add_column('stats_four', sa.Column('s4_total_wins', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stats_four_s4_total_kills'), 'stats_four', ['s4_total_kills'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_total_matches'), 'stats_four', ['s4_total_matches'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_total_wins'), 'stats_four', ['s4_total_wins'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_four_s4_total_wins'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_total_matches'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_total_kills'), table_name='stats_four')
    op.drop_column('stats_four', 's4_total_wins')
    op.drop_column('stats_four', 's4_total_matches')
    op.drop_column('stats_four', 's4_total_kills')
    # ### end Alembic commands ###
