"""adding win percentage back pt 2

Revision ID: 198228c16c4b
Revises: 23f0e0119749
Create Date: 2018-04-30 14:42:54.360612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198228c16c4b'
down_revision = '23f0e0119749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('life_duo_wr', sa.Float(), nullable=True))
    op.add_column('stats', sa.Column('life_solo_wr', sa.Float(), nullable=True))
    op.add_column('stats', sa.Column('life_squad_wr', sa.Float(), nullable=True))
    op.add_column('stats', sa.Column('life_wr', sa.Float(), nullable=True))
    op.create_index(op.f('ix_stats_life_duo_wr'), 'stats', ['life_duo_wr'], unique=False)
    op.create_index(op.f('ix_stats_life_solo_wr'), 'stats', ['life_solo_wr'], unique=False)
    op.create_index(op.f('ix_stats_life_squad_wr'), 'stats', ['life_squad_wr'], unique=False)
    op.create_index(op.f('ix_stats_life_wr'), 'stats', ['life_wr'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_life_wr'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_squad_wr'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_solo_wr'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_duo_wr'), table_name='stats')
    op.drop_column('stats', 'life_wr')
    op.drop_column('stats', 'life_squad_wr')
    op.drop_column('stats', 'life_solo_wr')
    op.drop_column('stats', 'life_duo_wr')
    # ### end Alembic commands ###
