"""adding matches played stat to all modes

Revision ID: 213637bd20e0
Revises: 8b543fb2ed1e
Create Date: 2018-04-30 14:10:25.818049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213637bd20e0'
down_revision = '8b543fb2ed1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('life_duo_matches', sa.Integer(), nullable=True))
    op.add_column('stats', sa.Column('life_solo_matches', sa.Integer(), nullable=True))
    op.add_column('stats', sa.Column('life_squad_matches', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stats_life_duo_matches'), 'stats', ['life_duo_matches'], unique=False)
    op.create_index(op.f('ix_stats_life_solo_matches'), 'stats', ['life_solo_matches'], unique=False)
    op.create_index(op.f('ix_stats_life_squad_matches'), 'stats', ['life_squad_matches'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_life_squad_matches'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_solo_matches'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_duo_matches'), table_name='stats')
    op.drop_column('stats', 'life_squad_matches')
    op.drop_column('stats', 'life_solo_matches')
    op.drop_column('stats', 'life_duo_matches')
    # ### end Alembic commands ###
