"""adding win percentage back

Revision ID: 23f0e0119749
Revises: 213637bd20e0
Create Date: 2018-04-30 14:29:32.614061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f0e0119749'
down_revision = '213637bd20e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('duo_wr', sa.Float(), nullable=True))
    op.add_column('stats', sa.Column('solo_wr', sa.Float(), nullable=True))
    op.add_column('stats', sa.Column('squad_wr', sa.Float(), nullable=True))
    op.create_index(op.f('ix_stats_duo_wr'), 'stats', ['duo_wr'], unique=False)
    op.create_index(op.f('ix_stats_solo_wr'), 'stats', ['solo_wr'], unique=False)
    op.create_index(op.f('ix_stats_squad_wr'), 'stats', ['squad_wr'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_squad_wr'), table_name='stats')
    op.drop_index(op.f('ix_stats_solo_wr'), table_name='stats')
    op.drop_index(op.f('ix_stats_duo_wr'), table_name='stats')
    op.drop_column('stats', 'squad_wr')
    op.drop_column('stats', 'solo_wr')
    op.drop_column('stats', 'duo_wr')
    # ### end Alembic commands ###
