"""changing s3 total matches to Int

Revision ID: 3510d57f6c18
Revises: 198228c16c4b
Create Date: 2018-04-30 18:45:15.559254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3510d57f6c18'
down_revision = '198228c16c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('s3_total_matchesnew', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stats_s3_total_matchesnew'), 'stats', ['s3_total_matchesnew'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_s3_total_matchesnew'), table_name='stats')
    op.drop_column('stats', 's3_total_matchesnew')
    # ### end Alembic commands ###
