"""init

Revision ID: 3b77bec9f2d0
Revises: 
Create Date: 2018-04-23 00:26:34.647596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b77bec9f2d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(length=64), nullable=True),
    sa.Column('solo_wins', sa.Integer(), nullable=True),
    sa.Column('solo_kills', sa.Integer(), nullable=True),
    sa.Column('solo_kpm', sa.Float(), nullable=True),
    sa.Column('solo_kd', sa.Float(), nullable=True),
    sa.Column('duo_wins', sa.Integer(), nullable=True),
    sa.Column('duo_kills', sa.Integer(), nullable=True),
    sa.Column('duo_kpm', sa.Float(), nullable=True),
    sa.Column('duo_kd', sa.Float(), nullable=True),
    sa.Column('squad_wins', sa.Integer(), nullable=True),
    sa.Column('squad_kills', sa.Integer(), nullable=True),
    sa.Column('squad_kpm', sa.Float(), nullable=True),
    sa.Column('squad_kd', sa.Float(), nullable=True),
    sa.Column('life_wins', sa.Integer(), nullable=True),
    sa.Column('life_kills', sa.Integer(), nullable=True),
    sa.Column('life_kpm', sa.Float(), nullable=True),
    sa.Column('life_kd', sa.Float(), nullable=True),
    sa.Column('life_matches', sa.Integer(), nullable=True),
    sa.Column('life_solo_wins', sa.Integer(), nullable=True),
    sa.Column('life_solo_kills', sa.Integer(), nullable=True),
    sa.Column('life_solo_kd', sa.Float(), nullable=True),
    sa.Column('pic', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stats_duo_kd'), 'stats', ['duo_kd'], unique=False)
    op.create_index(op.f('ix_stats_duo_kills'), 'stats', ['duo_kills'], unique=False)
    op.create_index(op.f('ix_stats_duo_kpm'), 'stats', ['duo_kpm'], unique=False)
    op.create_index(op.f('ix_stats_duo_wins'), 'stats', ['duo_wins'], unique=False)
    op.create_index(op.f('ix_stats_life_kd'), 'stats', ['life_kd'], unique=False)
    op.create_index(op.f('ix_stats_life_kills'), 'stats', ['life_kills'], unique=False)
    op.create_index(op.f('ix_stats_life_kpm'), 'stats', ['life_kpm'], unique=False)
    op.create_index(op.f('ix_stats_life_matches'), 'stats', ['life_matches'], unique=False)
    op.create_index(op.f('ix_stats_life_solo_kd'), 'stats', ['life_solo_kd'], unique=False)
    op.create_index(op.f('ix_stats_life_solo_kills'), 'stats', ['life_solo_kills'], unique=False)
    op.create_index(op.f('ix_stats_life_solo_wins'), 'stats', ['life_solo_wins'], unique=False)
    op.create_index(op.f('ix_stats_life_wins'), 'stats', ['life_wins'], unique=False)
    op.create_index(op.f('ix_stats_pic'), 'stats', ['pic'], unique=False)
    op.create_index(op.f('ix_stats_player'), 'stats', ['player'], unique=False)
    op.create_index(op.f('ix_stats_solo_kd'), 'stats', ['solo_kd'], unique=False)
    op.create_index(op.f('ix_stats_solo_kills'), 'stats', ['solo_kills'], unique=False)
    op.create_index(op.f('ix_stats_solo_kpm'), 'stats', ['solo_kpm'], unique=False)
    op.create_index(op.f('ix_stats_solo_wins'), 'stats', ['solo_wins'], unique=False)
    op.create_index(op.f('ix_stats_squad_kd'), 'stats', ['squad_kd'], unique=False)
    op.create_index(op.f('ix_stats_squad_kills'), 'stats', ['squad_kills'], unique=False)
    op.create_index(op.f('ix_stats_squad_kpm'), 'stats', ['squad_kpm'], unique=False)
    op.create_index(op.f('ix_stats_squad_wins'), 'stats', ['squad_wins'], unique=False)
    op.create_table('win_feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_win_feed_log'), 'win_feed', ['log'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_win_feed_log'), table_name='win_feed')
    op.drop_table('win_feed')
    op.drop_index(op.f('ix_stats_squad_wins'), table_name='stats')
    op.drop_index(op.f('ix_stats_squad_kpm'), table_name='stats')
    op.drop_index(op.f('ix_stats_squad_kills'), table_name='stats')
    op.drop_index(op.f('ix_stats_squad_kd'), table_name='stats')
    op.drop_index(op.f('ix_stats_solo_wins'), table_name='stats')
    op.drop_index(op.f('ix_stats_solo_kpm'), table_name='stats')
    op.drop_index(op.f('ix_stats_solo_kills'), table_name='stats')
    op.drop_index(op.f('ix_stats_solo_kd'), table_name='stats')
    op.drop_index(op.f('ix_stats_player'), table_name='stats')
    op.drop_index(op.f('ix_stats_pic'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_wins'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_solo_wins'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_solo_kills'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_solo_kd'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_matches'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_kpm'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_kills'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_kd'), table_name='stats')
    op.drop_index(op.f('ix_stats_duo_wins'), table_name='stats')
    op.drop_index(op.f('ix_stats_duo_kpm'), table_name='stats')
    op.drop_index(op.f('ix_stats_duo_kills'), table_name='stats')
    op.drop_index(op.f('ix_stats_duo_kd'), table_name='stats')
    op.drop_table('stats')
    # ### end Alembic commands ###
