"""lifetime duo and squad

Revision ID: 781998b42b39
Revises: 3b77bec9f2d0
Create Date: 2018-04-26 13:01:24.647402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781998b42b39'
down_revision = '3b77bec9f2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('life_duo_kd', sa.Float(), nullable=True))
    op.add_column('stats', sa.Column('life_duo_kills', sa.Integer(), nullable=True))
    op.add_column('stats', sa.Column('life_duo_wins', sa.Integer(), nullable=True))
    op.add_column('stats', sa.Column('life_squad_kd', sa.Float(), nullable=True))
    op.add_column('stats', sa.Column('life_squad_kills', sa.Integer(), nullable=True))
    op.add_column('stats', sa.Column('life_squad_wins', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stats_life_duo_kd'), 'stats', ['life_duo_kd'], unique=False)
    op.create_index(op.f('ix_stats_life_duo_kills'), 'stats', ['life_duo_kills'], unique=False)
    op.create_index(op.f('ix_stats_life_duo_wins'), 'stats', ['life_duo_wins'], unique=False)
    op.create_index(op.f('ix_stats_life_squad_kd'), 'stats', ['life_squad_kd'], unique=False)
    op.create_index(op.f('ix_stats_life_squad_kills'), 'stats', ['life_squad_kills'], unique=False)
    op.create_index(op.f('ix_stats_life_squad_wins'), 'stats', ['life_squad_wins'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_life_squad_wins'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_squad_kills'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_squad_kd'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_duo_wins'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_duo_kills'), table_name='stats')
    op.drop_index(op.f('ix_stats_life_duo_kd'), table_name='stats')
    op.drop_column('stats', 'life_squad_wins')
    op.drop_column('stats', 'life_squad_kills')
    op.drop_column('stats', 'life_squad_kd')
    op.drop_column('stats', 'life_duo_wins')
    op.drop_column('stats', 'life_duo_kills')
    op.drop_column('stats', 'life_duo_kd')
    # ### end Alembic commands ###
