"""adding matches to each season 3 mode

Revision ID: 8b543fb2ed1e
Revises: 781998b42b39
Create Date: 2018-04-30 13:52:34.759928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b543fb2ed1e'
down_revision = '781998b42b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('duo_matches', sa.Integer(), nullable=True))
    op.add_column('stats', sa.Column('s3_total_kd', sa.Float(), nullable=True))
    op.add_column('stats', sa.Column('s3_total_kills', sa.Integer(), nullable=True))
    op.add_column('stats', sa.Column('s3_total_matches', sa.Float(), nullable=True))
    op.add_column('stats', sa.Column('s3_total_wins', sa.Integer(), nullable=True))
    op.add_column('stats', sa.Column('solo_matches', sa.Integer(), nullable=True))
    op.add_column('stats', sa.Column('squad_matches', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stats_duo_matches'), 'stats', ['duo_matches'], unique=False)
    op.create_index(op.f('ix_stats_s3_total_kd'), 'stats', ['s3_total_kd'], unique=False)
    op.create_index(op.f('ix_stats_s3_total_kills'), 'stats', ['s3_total_kills'], unique=False)
    op.create_index(op.f('ix_stats_s3_total_matches'), 'stats', ['s3_total_matches'], unique=False)
    op.create_index(op.f('ix_stats_s3_total_wins'), 'stats', ['s3_total_wins'], unique=False)
    op.create_index(op.f('ix_stats_solo_matches'), 'stats', ['solo_matches'], unique=False)
    op.create_index(op.f('ix_stats_squad_matches'), 'stats', ['squad_matches'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_squad_matches'), table_name='stats')
    op.drop_index(op.f('ix_stats_solo_matches'), table_name='stats')
    op.drop_index(op.f('ix_stats_s3_total_wins'), table_name='stats')
    op.drop_index(op.f('ix_stats_s3_total_matches'), table_name='stats')
    op.drop_index(op.f('ix_stats_s3_total_kills'), table_name='stats')
    op.drop_index(op.f('ix_stats_s3_total_kd'), table_name='stats')
    op.drop_index(op.f('ix_stats_duo_matches'), table_name='stats')
    op.drop_column('stats', 'squad_matches')
    op.drop_column('stats', 'solo_matches')
    op.drop_column('stats', 's3_total_wins')
    op.drop_column('stats', 's3_total_matches')
    op.drop_column('stats', 's3_total_kills')
    op.drop_column('stats', 's3_total_kd')
    op.drop_column('stats', 'duo_matches')
    # ### end Alembic commands ###
