"""tracking highest kill counts from games

Revision ID: cbe152b21861
Revises: 1508333f895d
Create Date: 2018-05-04 16:02:36.381884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe152b21861'
down_revision = '1508333f895d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats_four', sa.Column('s4_duo_killsmax', sa.Integer(), nullable=True))
    op.add_column('stats_four', sa.Column('s4_solo_killsmax', sa.Integer(), nullable=True))
    op.add_column('stats_four', sa.Column('s4_squad_killsmax', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stats_four_s4_duo_killsmax'), 'stats_four', ['s4_duo_killsmax'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_solo_killsmax'), 'stats_four', ['s4_solo_killsmax'], unique=False)
    op.create_index(op.f('ix_stats_four_s4_squad_killsmax'), 'stats_four', ['s4_squad_killsmax'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_four_s4_squad_killsmax'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_solo_killsmax'), table_name='stats_four')
    op.drop_index(op.f('ix_stats_four_s4_duo_killsmax'), table_name='stats_four')
    op.drop_column('stats_four', 's4_squad_killsmax')
    op.drop_column('stats_four', 's4_solo_killsmax')
    op.drop_column('stats_four', 's4_duo_killsmax')
    # ### end Alembic commands ###
