"""adding player column to season4 table

Revision ID: d8f37f5b7fa4
Revises: 096e9653b7a4
Create Date: 2018-05-01 17:02:36.774461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f37f5b7fa4'
down_revision = '096e9653b7a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats_four', sa.Column('player', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_stats_four_player'), 'stats_four', ['player'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_four_player'), table_name='stats_four')
    op.drop_column('stats_four', 'player')
    # ### end Alembic commands ###
